server:
  port: 6060
dubbo:
  application:
    name: order-server
    qos-port: 33333
  registry:
    address: 192.168.0.10:2181,192.168.0.11:2181,192.168.0.12:2181
    protocol: zookeeper
  consumer: # 超时时间定义为5秒
    timeout: 5000